name: Feature Report
description: Request new Feature
title: "[FEATURE]: "
labels: ["🌱기능🌱"]
body:
  - type: markdown
    attributes:
      value: |
        자자, 화이팅입니다. 서재완씨.
  - type: textarea
    id: new-feature
    attributes:
      label: 작업 사항 
      description: 어떤 기능을 추가할건가요? 
      placeholder: 여기에 기능 입력
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: Todo
      description: 작업사항을 나누어 작성해주세요! 
      value: |
        - [ ] todo1
  - type: textarea
    id: etc
    attributes:
      label: 기타사항
      description: 추가로 기록이 필요한 경우 작성해주세요!
      placeholder: 여기에 기록 입력
